version: '3.8'
services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - lms_network

  server:
    build: ./server
    container_name: lms_server
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    networks:
      - lms_network
    depends_on:
      - mongodb

  client:
    build: ./client
    container_name: lms_client
    env_file:
      - ./client/.env
    ports:
      - "3000:80"
    networks:
      - lms_network
    depends_on:
      - server

volumes:
  mongodb_data:

networks:
  lms_network:
    driver: bridge
